version: 2
sources:
- name: rakam_supersonic
  database: rakam
  schema: supersonic
  meta:
    hidden: false
  tables:
  - name: related_channel_recommendation_selected
    meta:
      measures:
        count_of_rows:
          aggregation: count
          type: double
        sum_of_schema_v:
          dimension: schema_v
          aggregation: sum
          type: double
        sum_of_number_of_favorites:
          dimension: number_of_favorites
          aggregation: sum
          type: double
        sum_of_experiment_group:
          dimension: experiment_group
          aggregation: sum
          type: double
    columns:
    - name: schema_v
      meta:
        type: double
    - name: view_path
      meta:
        type: string
    - name: sign_up_type
      meta:
        type: string
    - name: device_type
      meta:
        type: string
    - name: number_of_favorites
      meta:
        type: double
    - name: user_id
      meta:
        type: string
    - name: event_name
      meta:
        type: string
    - name: _time
      meta:
        type: timestamp
    - name: year
      meta:
        type: string
    - name: experiment_group
      meta:
        type: double
    - name: id
      meta:
        type: string
    - name: location
      meta:
        type: string
    - name: device_id
      meta:
        type: string
    - name: event_type
      meta:
        type: string
    - name: timestamp
      meta:
        type: timestamp
    - name: ab_testing_experiment
      meta:
        type: array_string
    - name: app_version
      meta:
        type: string
    - name: _user
      meta:
        type: string
    - name: show_id
      meta:
        type: string
    - name: device_connection
      meta:
        type: string
    - name: type
      meta:
        type: string
    - name: app_build_type
      meta:
        type: string
    - name: show_name
      meta:
        type: string
    - name: gender
      meta:
        type: string
    - name: platform
      meta:
        type: string
    - name: $server_time
      meta:
        label: $server_time
        type: timestamp
